name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
